apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: account-api
data:
  application.properties: |
    user.Administrator.password=$secret{ADMIN_PASSWORD}

    artConnection.sttAccountAPI.sttAccountAPI.api.connections.accountAPI_sqlsever.connectionEnabled=true
    artConnection.sttAccountAPI.sttAccountAPI.api.connections.accountAPI_sqlsever.connectionSettings.serverName=$secret{DB_SERVER}
    artConnection.sttAccountAPI.sttAccountAPI.api.connections.accountAPI_sqlsever.connectionSettings.portNumber=$secret{DB_PORT}
    artConnection.sttAccountAPI.sttAccountAPI.api.connections.accountAPI_sqlsever.connectionSettings.user=$secret{DB_USERNAME}
    artConnection.sttAccountAPI.sttAccountAPI.api.connections.accountAPI_sqlsever.connectionSettings.password=$secret{DB_PASSWORD}
    artConnection.sttAccountAPI.sttAccountAPI.api.connections.accountAPI_sqlsever.connectionSettings.databaseName=sandbox
    artConnection.sttAccountAPI.sttAccountAPI.api.connections.accountAPI_sqlsever.connectionSettings.otherProperties= 

    settings.watt.server.audit.service.include=sttAccountAPI.*
    settings.watt.server.audit.service.exclude=wm.,com.,pub.

    globalvariable.SERVER.value=$env{SERVER}
---
# To create the gh-regcred secret, submit this command:
# kubectl create secret docker-registry gh-regcred --docker-server=${GH_CR_SERVER} --docker-username=${GH_CR_USERNAME} --docker-password=${GH_CR_PASSWORD}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-api
  labels:
    app.kubernetes.io/instance: account-api
    app.kubernetes.io/name: microservicesruntime
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: account-api
      app.kubernetes.io/name: microservicesruntime
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: account-api
        app.kubernetes.io/name: microservicesruntime
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '5555'
        prometheus.io/scheme: http
    spec:
      serviceAccountName: account-api
      restartPolicy: Always
      imagePullSecrets:
        - name: gh-regcred
      securityContext: {}  
      containers:
        - name: account-api
          image: ghcr.io/staillanibm/msr-account-api:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - name: application-properties
              mountPath: /opt/softwareag/IntegrationServer/application.properties
              subPath:   application.properties
              readOnly:  true
            - name: edge-secrets
              mountPath: /etc/secrets
          ports:
            - name: https
              containerPort: 5543
              protocol: TCP
            - name: http
              containerPort: 5555
              protocol: TCP
            - name: diag
              containerPort: 9999
              protocol: TCP
          env:
            - name: SERVER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            tcpSocket:
              port: http
            timeoutSeconds: 2
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 15
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 32
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2048Mi
      volumes:
        - name: application-properties
          configMap:
            name: account-api
            items:
            - key:  application.properties
              path: application.properties
        - name: edge-secrets
          secret:
            secretName: account-api
---
apiVersion: v1
kind: Service
metadata:
  name: account-api
  labels:
    app.kubernetes.io/instance: account-api
    app.kubernetes.io/name: microservicesruntime
spec:
  selector:
    app.kubernetes.io/instance: account-api
    app.kubernetes.io/name: microservicesruntime
  ports:
    - name: http
      port: 5555
      targetPort: 5555

